#!/usr/bin/python

import sys
import subprocess

sig = sys.argv[1].split("=")[1]
cyc = sys.argv[2]
bina = sys.argv[3]

p = subprocess.check_call("riscv64-unknown-elf-nm " + bina + " | grep 'begin_signature' > startSIG", shell=True)
p = subprocess.check_call("riscv64-unknown-elf-nm " + bina + " | grep 'end_signature' > endSIG", shell=True)

p = subprocess.check_call("../riscv-qemu/riscv64-softmmu/qemu-system-riscv64 -nographic -kernel " + bina + " 2> " + sig, shell=True)
